name: "Conftest policy check"

on:
  workflow_dispatch:
    inputs:
      scenario:
        description: "Choose Terraform scenario"
        type: choice
        required: true
        default: compliant
        options:
          - compliant
          - noncompliant

permissions:
  id-token: write
  contents: read

jobs:
  conftest:
    runs-on: ubuntu-latest

    env:
      TF_VAR_region: ${{ vars.TF_VAR_region }}
      TF_VAR_ami: ${{ vars.TF_VAR_ami }}
      TF_VAR_instance_type: ${{ vars.TF_VAR_instance_type }}
      TF_VAR_MySessionManagerRole: ${{ vars.TF_VAR_MySessionManagerRole }}
      TF_VAR_vpc_cidr: ${{ vars.TF_VAR_vpc_cidr }}
      TF_VAR_int1_cidr: ${{ vars.TF_VAR_int1_cidr }}
      TF_VAR_int2_cidr: ${{ vars.TF_VAR_int2_cidr }}
      TF_VAR_dmz1_cidr: ${{ vars.TF_VAR_dmz1_cidr }}
      TF_VAR_dmz2_cidr: ${{ vars.TF_VAR_dmz2_cidr }}
      TF_VAR_ssm_profile: ${{ vars.TF_VAR_ssm_profile }}
      TF_VAR_home_ip: ${{ vars.TF_VAR_home_ip }}
      TF_VAR_rds_username: ${{ vars.TF_VAR_rds_username }}
      TF_VAR_deployment_role: ${{ vars.TF_VAR_deployment_role }}
      TF_VAR_rds_password: ${{ secrets.TF_VAR_RDS_SECRET }}

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v3

      - name: "Install Conftest"
        run: |
          set -euo pipefail
          V=0.66.0
          curl -L -o conftest.tar.gz "https://github.com/open-policy-agent/conftest/releases/download/v${V}/conftest_${V}_Linux_x86_64.tar.gz"
          tar -xzf conftest.tar.gz conftest
          sudo mv conftest /usr/local/bin/
          conftest --version

      - name: "Configure AWS credentials (OIDC)"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::<ACCOUNT_ID1>}:role/github-terraform-ci-ops
          aws-region: eu-west-2

      # Assumes new structure like:
      # terraform/noncompliant/...
      # terraform/compliant/...
      # policy/...
      # input/...
      #
      # If you're only running the noncompliant scenario for now, keep SCENARIO=noncompliant.
      # Later you can matrix this.
      - name: "Set scenario"
        run: echo "SCENARIO=${{ inputs.scenario }}" >> $GITHUB_ENV

      
      - name: "Lab root"
        run: echo LAB_ROOT=${{ github.workspace }} >> $GITHUB_ENV

      - name: "Terraform init and plan to JSON"
        env:
          TF_VAR_rds_password: ${{ secrets.TF_VAR_RDS_SECRET }}
        run: |
          set -euo pipefail
          mkdir -p input
          terraform -chdir=terraform/scenarios/${SCENARIO} init -input=false -reconfigure \
          -backend-config="bucket=${{ vars.TF_STATE_BUCKET }}" \
          -backend-config="region=${{ vars.TF_STATE_REGION }}" \
          -backend-config="dynamodb_table=${{ vars.TF_LOCK_TABLE }}" \
          -backend-config="key=grc-aws-automation/${SCENARIO}/terraform.tfstate"
          terraform -chdir=terraform/scenarios/${SCENARIO} plan -input=false -out=$LAB_ROOT/input/tfplan.bin
          terraform -chdir=terraform/scenarios/${SCENARIO} show -json $LAB_ROOT/input/tfplan.bin > input/tfplan.json

      - name: "Conftest test (namespace plan)"
        run: |
          set -euo pipefail
          conftest test input/tfplan.json -p policy --all-namespaces

      - name: Terraform Apply
        env:
          TF_VAR_rds_password: ${{ secrets.TF_VAR_RDS_SECRET }}
        run: |
          terraform -chdir=terraform/scenarios/${SCENARIO} apply -input=false -auto-approve $LAB_ROOT/input/tfplan.bin
