name: Destroy (manual)

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type DESTROY to confirm"
        required: true
        default: "no"

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    if: ${{ github.event.inputs.confirm == 'DESTROY' }}
    runs-on: ubuntu-latest

    env:
      TF_IN_AUTOMATION: "true"
      TF_INPUT: "false"

      # Terraform input variables (repo variables + secret)
      TF_VAR_region: ${{ vars.TF_VAR_region }}
      TF_VAR_ami: ${{ vars.TF_VAR_ami }}
      TF_VAR_instance_type: ${{ vars.TF_VAR_instance_type }}
      TF_VAR_MySessionManagerRole: ${{ vars.TF_VAR_MySessionManagerRole }}
      TF_VAR_vpc_cidr: ${{ vars.TF_VAR_vpc_cidr }}
      TF_VAR_int1_cidr: ${{ vars.TF_VAR_int1_cidr }}
      TF_VAR_int2_cidr: ${{ vars.TF_VAR_int2_cidr }}
      TF_VAR_dmz1_cidr: ${{ vars.TF_VAR_dmz1_cidr }}
      TF_VAR_dmz2_cidr: ${{ vars.TF_VAR_dmz2_cidr }}
      TF_VAR_ssm_profile: ${{ vars.TF_VAR_ssm_profile }}
      TF_VAR_home_ip: ${{ vars.TF_VAR_home_ip }}
      TF_VAR_rds_username: ${{ vars.TF_VAR_rds_username }}
      TF_VAR_deployment_role: ${{ vars.TF_VAR_deployment_role }}
      TF_VAR_rds_password: ${{ secrets.TF_VAR_RDS_SECRET }}

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::526053389648:role/github-terraform-ci-ops
          aws-region: eu-west-2

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init (noncompliant)
        run: |
          terraform -chdir=terraform/scenarios/noncompliant init -reconfigure -input=false \
            -backend-config="bucket=${{ vars.TF_STATE_BUCKET }}" \
            -backend-config="region=${{ vars.TF_STATE_REGION }}" \
            -backend-config="dynamodb_table=${{ vars.TF_LOCK_TABLE }}" \
            -backend-config="key=grc-aws-automation/noncompliant/terraform.tfstate"

      - name: Sanity check - show what Terraform thinks exists
        run: |
          terraform -chdir=terraform/scenarios/noncompliant state list
          
      - name: Terraform Destroy (noncompliant)
        run: |
          terraform -chdir=terraform/scenarios/noncompliant destroy -auto-approve -input=false
